import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Axcel High-Performance System color tokens
        'surface-container-lowest': '#100d17',
        'surface-container-low': '#1d1a25',
        'surface-container': '#211e29',
        'surface-container-high': '#2c2834',
        'surface-container-highest': '#37333f',
        'surface-dim': '#15121c',
        'surface': '#15121c',
        'surface-bright': '#3b3743',
        'surface-variant': '#37333f',
        'on-surface': '#e7e0ef',
        'on-surface-variant': '#cbc3d9',
        'background': '#15121c',
        'on-background': '#e7e0ef',
        'primary': '#d0bcff',
        'on-primary': '#3b0091',
        'primary-container': '#7c3aff',
        'on-primary-container': '#f2e8ff',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5500ca',
        'secondary': '#d0bcff',
        'on-secondary': '#391a78',
        'secondary-container': '#523793',
        'on-secondary-container': '#c3abff',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#503590',
        'tertiary': '#ffb68e',
        'on-tertiary': '#532200',
        'tertiary-container': '#ae4e00',
        'on-tertiary-container': '#ffe7db',
        'tertiary-fixed': '#ffdbc9',
        'tertiary-fixed-dim': '#ffb68e',
        'on-tertiary-fixed': '#331200',
        'on-tertiary-fixed-variant': '#763300',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'outline': '#958da2',
        'outline-variant': '#4a4456',
        'inverse-surface': '#e7e0ef',
        'inverse-on-surface': '#322f3a',
        'inverse-primary': '#6f26f2',
        'surface-tint': '#d0bcff',
        // Extra semantic tokens
        'card': '#1a1a24',
        'elevated': '#252532',
        'muted': '#8e8da6',
        'accent': '#00e5a0',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
        'card': '16px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'display': ['var(--font-bebas-neue)', 'cursive'],
        'headline': ['var(--font-bebas-neue)', 'cursive'],
        'body': ['var(--font-dm-sans)', 'sans-serif'],
        'label': ['var(--font-dm-sans)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '48px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '32px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '28px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #7c3aff 0%, #d0bcff 100%)',
        'gradient-cta': 'linear-gradient(90deg, #7c3aff 0%, #00e5a0 100%)',
        'dot-pattern': 'radial-gradient(circle, #252532 1.5px, transparent 1.5px)',
      },
    },
  },
  plugins: [],
};

export default config;
